### ISSUE TITLE
Modconflict with manual attach

### ISSUE THREAD

**Issue by Menno58** [loki79uk/FS22_UniversalAutoload#14]
When loading a savegame with this autoload script and manual attach enabled I get this error message and the savegame won't load.

2022-02-25 14:21 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
My Games/FarmingSimulator2022/mods/FS22_manualAttach/src/vehicle/ManualAttachPowerTakeOff.lua:62: attempt to index local 'spec' (a nil value)

It only happens with the autoload mod all the other mods I have do not give this message.

**Comment by loki79uk** [comment]
There are a couple of mod conflicts that are likely to all be the same problem.  Hopefully knowing a few of them will make it easier to identify the problem, but I will update this issue again when I find it!

**Comment by loki79uk** [comment]
The good news is that this conflict seems to have been resolved by the latest game patch 1.3.0.0! :)

**Comment by loki79uk** [comment]
This seems to be fixed in: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.0.0-beta-update-002
Although (as per previous comment), I think it was actually the game update that resolved it.

**Comment by notendradon** [comment]
Still throws the error with the 005 update for me

2022-02-27 17:01 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
D:/Documents/My Games/FarmingSimulator2022/mods/FS22_manualAttach/src/vehicle/ManualAttachPowerTakeOff.lua:62: attempt to index local 'spec' (a nil value)

**Comment by loki79uk** [comment]
That is weird, it is still working for me?  Do you have any other mods installed?

**Comment by notendradon** [comment]
I do, I'll check them later. Disabling either UniversalAutoload or Manual Attach does however allow the save game to load without an error

**Comment by Menno58** [comment]
I think I might have accidentally left manual attach disabled and thought it was fixed. I now have the same error again. Apologies for the inconvenience

**Comment by loki79uk** [comment]
I managed to get the error from the shop screen. My game full of existing trailers was loading fine with both mods installed, but I get that error when a new vehicle loads into the shop.

**Comment by loki79uk** [comment]
The original error is resolved in this version:  https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.0.0-beta-update-007

The problem was that I was removing the 'onPostLoad' event listener during onLoad, and somehow that was affecting the onPostLoad event listener for ManualAttach.  I've seen something like this before where the event is removed from the list during an iterative loop, so one of the items is missed because the iterator/counter does not know that the loop has changed size. 

BUT - there is now an issue where Manual Attach does not detect the autoload trailers, so you are stuck with no way to detach the trailers. It still works on non-autoload trailers and implements.  I don't think there is anything I can do about that one though..?

**Comment by notendradon** [comment]
So I just tested this with all the supported trailers and can't reproduce it (on 009). I can attach and detach all of them fine with both mods running, loaded and unloaded trailers, bought before and after enabling the mods.

Only thing that doesn't work as expected: When attaching a trailer you have to hop in and out of the tractor to be able to un-/load the trailer from the outside, but I assume that there isn't really anything to be done about that.

**Comment by loki79uk** [comment]
It is weird that you get manual attach to work, it definitely want there for me.  I'll have another go this evening.

Sometimes it just doesn't refresh the keys at the right time.  My ugly solution previously was to constantly refresh the key bindings when on foot, but that caused other problems, so it seems like I can never win..  You can try moving away and back to the trailer on foot which should also work to refresh the menu.

**Comment by Menno58** [comment]
I have just tested it as well and everything was working for me too.

**Comment by loki79uk** [comment]
That is good news.  I'll start a new game from scratch and see if it was something weird in that particular save game causing it.

**Comment by loki79uk** [comment]
It works for me as well, happy days!!  All I can think of to explain the problem yesterday is maybe because I had saved the game while the conflict was still happening.  I went back to the previous save, loaded with Manual Attach and now both are working fine.
